### ISSUE TITLE
Battery pin connectors

### ISSUE THREAD

**Issue by abencomo** [ashtuchkin/vive-diy-position-sensor#12]
Hi Alex,

I hope you had a good time during your vacation, welcome back.  I noticed that you are not using the battery XT-60 connector; which makes sense since otherwise your station would have not been available to swap batteries.  Would you mind letting me know the pin connector are you using and did you purchased them from [here](https://www.mill-max.com/)?

Thanks, and best regards!
~~Al

**Comment by ashtuchkin** [comment]
Yeah, I had some good time, thanks :)

I'm actually using XT-60 in three places:

![image](https://cloud.githubusercontent.com/assets/627997/22403078/afb35314-e5c1-11e6-9d38-3c0eaa82061c.png)
![image](https://cloud.githubusercontent.com/assets/627997/22403081/b5e3532e-e5c1-11e6-850b-03612f23dfea.png)
![image](https://cloud.githubusercontent.com/assets/627997/22403084/bbdd1530-e5c1-11e6-95c2-ff573e3d82b9.png)

But for the connection between battery and copter, I'm using [these pins](https://www.digikey.com/product-detail/en/mill-max-manufacturing-corp/0851-0-15-20-82-14-11-0/ED90512-ND/2532965).  3x of them for each power wire (8x3= 24 Amps) and 1x for additional wires to balance charging.
