### ISSUE TITLE
rvdm88 gif: Wrong H sweep direction ?

### ISSUE THREAD

**Issue by DoNck** [ashtuchkin/vive-diy-position-sensor#19]
Hi there !

In the description, you are using a gif animation which I think is built from rvdm88's video. 

[![How it works](http://i.giphy.com/ijMzXRF3OYBZ6.gif)](https://www.youtube.com/watch?v=oqPaaMR4kY4)

Looking at a [960fps slow motion video](https://www.youtube.com/watch?v=avBt_P0wg_Y), I can see the wheels sweeping from left to right, and from bottom to top (looking at the optical parts).

So I'm pretty surprised by the direction of the horizontal sweep (the one highlighting the vertical plane) in the animation from rvdm88. I think it should go ***from left to right***.

Am I right ?

Note: I also posted [a comment](https://www.youtube.com/watch?v=J54dotTt7k0&lc=z234vvpxblb2c3wlhacdp435l13dswd3x0pf4vxaeipw03c010c) to ask the same question directly on rvdm88's last version of the video ["HTC Vive Lighthouse Chaperone tracking system Explained"](https://www.youtube.com/watch?v=J54dotTt7k0&lc=z234vvpxblb2c3wlhacdp435l13dswd3x0pf4vxaeipw03c010c).

PS: Thanks for sharing !

**Comment by ashtuchkin** [comment]
Yes! You're definitely right. It's happening from left to right if you're looking at base station from sensor point of view.
