### ISSUE TITLE
Can tracking be done on android?

### ISSUE THREAD

**Issue by GameFaceLabs** [ashtuchkin/vive-diy-position-sensor#23]
Title says it all

**Comment by ashtuchkin** [comment]
Theoretically yes. You'll need access to hardware timers, though. Precise
timing is critical.

**Comment by GameFaceLabs** [comment]
Interesting. As it happens, we build a standalone VR headset powered by
Android, which we have built from scratch. I would love to ask a few
questions if you had time

On Apr 24, 2017 5:49 PM, "Alexander Shtuchkin" <notifications@github.com>
wrote:
>
> Theoretically yes. You'll need access to hardware timers, though. Precise
> timing is critical.
>
> On Apr 23, 2017 2:18 PM, "GameFaceLabs" <notifications@github.com> wrote:
>
> > Title says it all
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/ashtuchkin/vive-diy-position-sensor/issues/23>, or
mute

**Comment by ashtuchkin** [comment]
Interesting, are you planning to support HTC Vive positioning? Sure, ask
any questions you have!
