### ISSUE TITLE
BPV22NF Photodiode angle of half sensitivity 60 instead of 120 deg?

### ISSUE THREAD

**Issue by donverduyn** [ashtuchkin/vive-diy-position-sensor#25]
We ordered all the components to replicate the board, but the specification of the BPV22NF photodiode explains that the angle of half sensitivity is not 120 degrees, and instead 60 degrees. Should we use more than three in an array?

**Comment by ashtuchkin** [comment]
AFAIK, it's 60 degrees in each direction, 120 total.

I used 3 of them and they covered the whole hemisphere without problems.

--
Alexander Shtuchkin
