### ISSUE TITLE
inaccurate position readings? movement along x results in difference on z coordinate.

### ISSUE THREAD

**Issue by donverduyn** [ashtuchkin/vive-diy-position-sensor#29]
Hi, 

After some testing, we have to conclude that the position coordinates are not valid. When we move our tracked object in space along x, the position on the z dimension changes too. Is this because of inaccurate base station coordinates or do we have to look elsewhere too?

**Comment by solinvictus21** [comment]
Just saw this. This is likely related to the issue that I just filed.

https://github.com/ashtuchkin/vive-diy-position-sensor/issues/34

**Comment by ashtuchkin** [comment]
I'm pretty sure it's not related to #34. I'd look into base station coordinates and rotation matrices first, yes. How large is the z dimension change vs x dimension?

**Comment by wouterpeetermans** [comment]
I'm having the same problem here. can you be more specific how I could troubleshoot this please?
