### ISSUE TITLE
Use 4.7pf cap instead og 5pf

### ISSUE THREAD

**Issue by TheBekker** [ashtuchkin/vive-diy-position-sensor#31]
I'm working on building the module, but i dont have any 5pf caps, would it make a difference to use 4.7pf instead? (i can only find 5pf on digikey, but the shipping is like 20x the cost of the parts)

**Comment by ashtuchkin** [comment]
Yes, I think it should work. I'm not an electronics guru, though :)

**Comment by TheBekker** [comment]
I'm guessing its only for clearing up the signal noise?
I will try it out, and let you know how it goes :)

**Comment by ashtuchkin** [comment]
Thanks!
