### ISSUE TITLE
Linux install issue

### ISSUE THREAD

**Issue by DanielArnett** [ashtuchkin/vive-diy-position-sensor#32]
`make: *** No rule to make target `vive-diy-position-sensor-upload'.  Stop.`

Ubuntu 14.04, seems to be compiling properly.

**Comment by DanielArnett** [comment]
I seem to be able to upload hex files with the [teensyduino uploader](https://www.pjrc.com/teensy/td_download.html), so I guess I'll stick to that for now.

**Comment by ashtuchkin** [comment]
Check you have a `tyc` command-line uploader (see https://github.com/Koromix/ty), placed into `/usr/local/bin/`. Regular teensyduino uploader works as well, yep!
