### ISSUE TITLE
TeensyLC compatibility?

### ISSUE THREAD

**Issue by SkaveRat** [ashtuchkin/vive-diy-position-sensor#35]
I have an LC lying around and am wondering if it's possible to make the code compatible with it.

I've done a fair bit of vive tracking stuff myself on the board and it should be possible, the compiled hex just isn't compatible.

I don't know enough about the platform and cmake to see what has to be changed to get an LC compatible hex. Can anyone help me out?

**Comment by ashtuchkin** [comment]
Nah, TeensyLC would be pretty hard to support as it's a different architecture.
