### ISSUE TITLE
Not understanding how to setup software part.

### ISSUE THREAD

**Issue by timfrans** [ashtuchkin/vive-diy-position-sensor#37]
Hi,

Currently I am trying to setup the software part of this project. 
I am working with windows.
Currently I have setup 2 system variables:
- cmake=C:\Program Files\CMake\bin\cmake
- PLATFORM=teensy

I try to run CMake with the configurations you can find in the picture.
![cmake](https://user-images.githubusercontent.com/22496040/33894210-affc8ae8-df5d-11e7-9b51-a8efa43a6208.PNG)

As you can see it gives an error.
I copied the ninja.exe file into the vive-diy-position-sensor. Actually I do not understand what to do with the ninja.exe

also, if i try to run `cmake -G Ninja .. -DPLATFORM=Teensy`, it gives me an error that the command cmake is not found.

I hope you can help me :)
thx!

# Edit:
I think I got it figured out with the system variables. When run the command `cmake -G Ninja .. -DPLATFORM=Teensy` it still fails.

**CMakeError.txt**
> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: C:/Program Files (x86)/GNU Tools ARM Embedded/6 2017-q2-update/bin/arm-none-eabi-gcc.exe 
Build flags: -O2;-Wall;-ffunction-sections;-fdata-sections;-Wstack-usage=256;-mcpu=cortex-m4;-mthumb;-mfp16-format=ieee
Id flags:  
The output was:
1
c:/program files (x86)/gnu tools arm embedded/6 2017-q2-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m\libc.a(lib_a-exit.o): In function `exit':
exit.c:(.text.exit+0x16): undefined reference to `_exit'
collect2.exe: error: ld returned 1 exit status
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: C:/Program Files (x86)/GNU Tools ARM Embedded/6 2017-q2-update/bin/arm-none-eabi-g++.exe 
Build flags: -O2;-Wall;-ffunction-sections;-fdata-sections;-Wstack-usage=256;-mcpu=cortex-m4;-mthumb;-mfp16-format=ieee;-fno-rtti;-fsingle-precision-constant;-Woverloaded-virtual
Id flags:  
The output was:
1
c:/program files (x86)/gnu tools arm embedded/6 2017-q2-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m\libc.a(lib_a-exit.o): In function `exit':
exit.c:(.text.exit+0x16): undefined reference to `_exit'
collect2.exe: error: ld returned 1 exit status
Determining if the C compiler works failed with the following output:
Change Dir: A:/hoge/17-18/ap vallet/vive-diy-position-sensor/build/CMakeFiles/CMakeTmp
Run Build Command:"A:/hoge/17-18/ap vallet/vive-diy-position-sensor/build/ninja.exe" "cmTC_b28c9"
[1/2] Building C object CMakeFiles/cmTC_b28c9.dir/testCCompiler.c.obj
[2/2] Linking C executable cmTC_b28c9
FAILED: cmTC_b28c9 
cmd.exe /C "cd . && C:\PROGRA~2\GNUTOO~1\62017-~1\bin\AR19DD~1.EXE -O2 -Wall -ffunction-sections -fdata-sections -Wstack-usage=256 -mcpu=cortex-m4 -mthumb -mfp16-format=ieee  -O2 -Wl,--gc-sections,--relax,--defsym=__rtc_localtime=0 -mcpu=cortex-m4 -mthumb -mfp16-format=ieee -TA:/hoge/17-18/ap vallet/vive-diy-position-sensor/libs/cores/teensy3/mk20dx256.ld CMakeFiles/cmTC_b28c9.dir/testCCompiler.c.obj  -o cmTC_b28c9   && cd ."
AR19DD~1.EXE: error: vallet/vive-diy-position-sensor/libs/cores/teensy3/mk20dx256.ld: No such file or directory
ninja: build stopped: subcommand failed.

My OS is Windows and I use CMake 3.10.1.
Thx :)

**Comment by jayaramanrp** [comment]
minimum cmake version is 3.12.

Add Cmake path to environmental variable.
try disabling the anti virus/ windows defender. 
execute cmake -G Ninja .. -DPLATFORM=Teensy command in cmd in build folder.
