### ISSUE TITLE
Arduino

### ISSUE THREAD

**Issue by bridger35** [ashtuchkin/vive-diy-position-sensor#39]
Is there a way to change this to Arduino?

**Comment by ashtuchkin** [comment]
Probably yes, for ARM-based Arduinos like Duo. But you'll have to create a
new "platform" directory with all the wiring specific to that controller.

--
Alexander Shtuchkin

**Comment by bridger35** [comment]
Thanks, I will look into that

**Comment by Aaryan90** [comment]
What advantage do ARM-based microcontrollers have over others (say ESP 8266, Arduino) for this specific implementation? I am looking to port this functionality into nrf52832 BLE chip.

**Comment by ashtuchkin** [comment]
Nice! I'm accepting pull requests if you're willing to share the code.

Wrt advantages - none really, except maybe that arm is generally faster
than arduinos and I worried that arduinos won't be fast enough. I also had
more experience with arm, so chose it as the target.

**Comment by jayaramanrp** [comment]
where we have to modify the code inorder to add IMU in this project?
