### ISSUE TITLE
Circuit layout

### ISSUE THREAD

**Issue by bridger35** [ashtuchkin/vive-diy-position-sensor#40]
I'm fairly new and was wondering if anyone could give me a guide on which holes to place what wires through, preferably accompanied with pictures.

**Comment by bridger35** [comment]
Maybe even a walkthrough video

**Comment by ashtuchkin** [comment]
Sorry, the board pictures in the readme is all I have for now. It should be
pretty straightforward to use that, plus schematics to reproduce the board.

--
Alexander Shtuchkin

**Comment by bridger35** [comment]
What about the wire going from i 10 to g6 is that just plain metal

**Comment by bridger35** [comment]
and 13 H to 9 H is that a double resistor and should the ends of the resistors be twisted

**Comment by ashtuchkin** [comment]
Yes yes and yes

One other option you have if you don't want to risk is to buy a sensor
TS3633-CM1 for like $10 and be sure it works.

**Comment by modulab** [comment]
Hi @ashtuchkin. can you update the circuit diagram with the pin number from the TLV2462IP? i think you are using it reversed. thank you

**Comment by ashtuchkin** [comment]
sorry don't have time for that, but willing to accept a PR
