### ISSUE TITLE
Steam VR

### ISSUE THREAD

**Issue by bridger35** [ashtuchkin/vive-diy-position-sensor#41]
Is this compatible with steam VR and is there any steps to get it to be compatible

**Comment by bridger35** [comment]
Or even osvr

**Comment by ashtuchkin** [comment]
Steam VR is used for calibration, after that the coordinate systems will be
the same. You can use the coordinates to control an object inside a SteamVR
app/game, but I can't give you exact steps.

--
Alexander Shtuchkin
