### ISSUE TITLE
Working for Teensy 3.6

### ISSUE THREAD

**Issue by mattgil23** [ashtuchkin/vive-diy-position-sensor#42]
I wanted to know if you considered using the Teensy 3.6 for the project. I love what you did and I'd like to do it with the CM1 sensors from triad and the 3.6 so I can have 6DOF tracking.

**Comment by alexhgian** [comment]
Also wondering if a Teensy-LC or similar will work trying to see how low cost I can make this build.

**Comment by kajep09** [comment]
It does work on the Teensy 3.6 with a few modifications. There is already a (closed) issue on the topic
https://github.com/ashtuchkin/vive-diy-position-sensor/issues/14
