### ISSUE TITLE
Is ESP8266 a good idea?

### ISSUE THREAD

**Issue by modulab** [ashtuchkin/vive-diy-position-sensor#43]
Do you think running the code on a ESP82266 or ESP32 would be a good idea ? The processor is almost twice as fast and it has more intrerup pins. And having direct wifi to broadcast the results it's priceless. What do you think?
thanks, Paul

**Comment by ashtuchkin** [comment]
If it has a good, stable hi-res timer, you should be good to go. You'll
have to reimplement the platform layer though, to access the hardware.

If you're interested in wifi, Photon board is also an option - it's one of
the already supported platforms and I had success sending location data
wirelessly with it.

--
Alexander Shtuchkin
