### ISSUE TITLE
Integrating to custom project

### ISSUE THREAD

**Issue by maker-ja** [ashtuchkin/vive-diy-position-sensor#49]
Hi people.

I am trying to integrate this code into a custom project. Basically, I wish to implement data acquisition from a 6 DOF inertial sensor in the same Teensy board that is running this code. I will have to enable I2C functionality for that. Further, I am looking to save data in a SD card which will require implementing SPI functionality.

I am new to embedded C and can't seem to understand the code structure, program flow. Could someone please elaborate on the same. TIA.

**Comment by ashtuchkin** [comment]
Sorry I haven't had time to write on the code structure, this is a hobby project that I'm not actively developing anymore.
