### ISSUE TITLE
Receiving sensor position data

### ISSUE THREAD

**Issue by HiruniNuwanthika** [ashtuchkin/vive-diy-position-sensor#50]
Hi,
I have cloned your project, compiled and created the hex file. How can I get the sensor position details in to the command line? 
Teensy_loader_Cli is not working on my PC.
I'm working on windows 10 and I have used Teensy 3.2 same as you. 

Thank you!!!

**Comment by ashtuchkin** [comment]
Hey Hiruni, does the official uploader app work for you?
https://www.pjrc.com/teensy/loader.html

Try to load some other program first, see if it works.

--
Alexander Shtuchkin

**Comment by HiruniNuwanthika** [comment]
Hi Alexander,
Thank you for answering..

I have tried few programs with Teensy loader as well as the Teensyduino. 
Blink _fast and Blink_slow programs with Teensy loader
Simple program with a photo diode circuit using Teensyuino.

What should I do to run a program in teensy_loader_cli? 
Can you please help me?

Thank you!!!

**Comment by HiruniNuwanthika** [comment]
I could solve the problem by reinstalling mingw in windows and running the teensy_loader_cli_windows. Now I can run .hex files from command prompt. 

How can I configure the module as you stated in https://github.com/ashtuchkin/vive-diy-position-sensor/blob/docs/docs/manual.md ?

Thank you!!!

**Comment by jayaramanrp** [comment]
how did you create .hex file?

**Comment by HiruniNuwanthika** [comment]
yes... It worked for me

**Comment by luoxz-ai** [comment]
How to use tycmd in windows ? 


How can I configure the module as you stated in https://github.com/ashtuchkin/vive-diy-position-sensor/blob/docs/docs/manual.md ?

**Comment by luoxz-ai** [comment]
Can the arduino serial port be able to view the debug output information?
