### ISSUE TITLE
Steamvr compatibility.

### ISSUE THREAD

**Issue by Lightsteed** [ashtuchkin/vive-diy-position-sensor#51]
Hi! If i build this device, will it be picked up as a tracker in steamvr and have its position be usable for things? Also,how would i get the data into the pc? Wirelss or usb (usb over ip) ? Thanks !

**Comment by ashtuchkin** [comment]
> will it be picked up as a tracker in steamvr
no

it's a low-level tracker, you decide how you get the data to pc - depending
on the chip it can be usb, uart, wifi, etc.

--
Alexander Shtuchkin

**Comment by Lightsteed** [comment]
Okay but assuming i get the data to the pc, will it be detected in steamvr? Sorry if u already answered it i just want to be sure.

**Comment by koen1993** [comment]
No.
