### ISSUE TITLE
Support for HTC Lighthouses 2.0

### ISSUE THREAD

**Issue by Mofeywalker** [ashtuchkin/vive-diy-position-sensor#52]
Hi, 

we have the new HTC Vive Pro set with the new lighthouses. I read that the new lighthouses use a new way to determine the position. Is it planned to support the new lighthouses in your software?

Best regards 
Moritz

**Comment by ashtuchkin** [comment]
Hey Moritz,

I'm not actively developing this project, plus don't have these new
goodies, so not likely. I'm open for pull requests, though!

Alex

**Comment by Mofeywalker** [comment]
Thanks Alex for answering that quickly!

Maybe someone has the new lighthouses and knows how to start to reverse engineer the protocol. Unfortunately we don't have the expertise and time to get this started.

Moritz

**Comment by koen1993** [comment]
Just wanted to add my 2 cent:
As far as i know, the 2.0 version now sends tracking information via the laser([mentioned here](https://skarredghost.com/2017/06/07/need-know-steamvr-tracking-2-0-will-foundation-vive-2/)), so it is a  different concept. 
Also if the problem mentioned in issue #34 is true, that means we dont have exact signals via the sensorboard(correct me if i am wrong) and that means it is probaly hard to read the exact information.

**Comment by Kjos** [comment]
If I'm guessing, it is now creating rays at 45 degrees from the motor, so it can fit two rays on one motor. Perhaps it's sending data by alternating rays: 45 degrees, 45, 45, -45, 45, -45, -45. If it only needs to send data on reset, that could suffice (1s / (avg of 8ms and 16ms =12) per sweep = 83bits/s

**Comment by luoxz-ai** [comment]
TS4231  Support for HTC Lighthouses 2.0
