### ISSUE TITLE
values given by vive-diy-position-sensor-geometry-getter

### ISSUE THREAD

**Issue by HiruniNuwanthika** [ashtuchkin/vive-diy-position-sensor#58]
What are the details included in the rotation matrix of each base station?

As I understood,
In https://github.com/ashtuchkin/vive-diy-position-sensor-geometry-getter it gives
First three values are the base station center points.
What I cannot understand is the next 6 values given. (values next to the word matrix)

Please explain it to me... 
Thank you!

**Comment by ashtuchkin** [comment]
It's the non-zero values of rotation matrix. A matrix is technically 3x3,
but the diagonal is zeros, so that leaves us with 6 numbers.
--
Alexander Shtuchkin

**Comment by HiruniNuwanthika** [comment]
Thank you for your explanation. But it will be more helpful if  you can give me a precise answer.
 What is the rotation matrix? is it X,Y,Z coordinate positions?

Thank you!

**Comment by ashtuchkin** [comment]
No, it's the rotation matrix - sines and cosines of corresponding angles. See https://en.wikipedia.org/wiki/Rotation_matrix#In_three_dimensions

I also see in the code that it expects 9 values there, sorry for confusion. 6 won't make it.

**Comment by HiruniNuwanthika** [comment]
I understood it completely... Thank you!!!

**Comment by HiruniNuwanthika** [comment]
According to my understanding, 
The values that are finally printed on the terminal is fix value, x, y, z, distance between 2 lines.
What is considered as the center point of those given values?

Thank you!!!

**Comment by ashtuchkin** [comment]
Not sure I understand the question.. xyz is the center. Distance between
the lines can be used to get a sense of accuracy of the position estimate
(although not directly).

**Comment by HiruniNuwanthika** [comment]
Thank you!!! I understood it...

Now I have another problem. Is there a method to track another set of three photodiodes? how should I do the configurations?
Thank you!!!

**Comment by ashtuchkin** [comment]
If you want to track them as independent objects, then just add them to
your config like this:
```
<your base station config>
sensor1 pin 12 positive
object1 sensor1
stream1 position object1 > usb_serial

sensor2 pin 13 positive
object2 sensor2
stream2 position object2 > usb_serial
```

If, on the other hand, you want to track them as a single object, then that
is not supported, sorry.

**Comment by ashtuchkin** [comment]
If you want to track them as independent objects, then just add them to
your config like this:

```
<your base station config>

sensor1 pin 12 positive  
object1 sensor1  
stream1 position object1 > usb_serial  

sensor2 pin 13 positive  
object2 sensor2  
stream2 position object2 > usb_serial  

..same thing for third and fourth ones  
```

If, on the other hand, you want to track them as a single object, then that is not supported, sorry.

**Comment by HiruniNuwanthika** [comment]
I want to track them as independent objects. 
Thank you  very much for your answer......

**Comment by HiruniNuwanthika** [comment]
I tried to configure for another set of photodiodes as you have explained in https://github.com/ashtuchkin/vive-diy-position-sensor/issues/58#issuecomment-418426095.
But the following error occurred. "Invalid threshold level. Supported value: 0-63".
How can I solve the problem? 

Thank you!!!

**Comment by ashtuchkin** [comment]
This is where it's coming from
https://github.com/ashtuchkin/vive-diy-position-sensor/blob/master/src/input.cpp#L103

What's the config you're using?

**Comment by jayaramanrp** [comment]
> If you want to track them as independent objects, then just add them to
> your config like this:
> 
> ```
> <your base station config>
> 
> sensor1 pin 12 positive  
> object1 sensor1  
> stream1 position object1 > usb_serial  
> 
> sensor2 pin 13 positive  
> object2 sensor2  
> stream2 position object2 > usb_serial  
> 

where to add the second independent object detail in the code? 
it would be helpful, if you share some knowledge.

**Comment by jayaramanrp** [comment]
> > If you want to track them as independent objects, then just add them to
> > your config like this:
> > ```
> > <your base station config>
> > 
> > sensor1 pin 12 positive  
> > object1 sensor1  
> > stream1 position object1 > usb_serial  
> > 
> > sensor2 pin 13 positive  
> > object2 sensor2  
> > stream2 position object2 > usb_serial  
> > ```
> 
> where to add the second independent object detail in the code?
> it would be helpful, if you share some knowledge.

got the answer:

open cmd (in windows) where TYtools are located.
enter into config mode by pressing "!"
then type the folowing : 
reset
#enter the based station geometry (that you calculated) or you can find the default in settings in src/settings.cpp:17 to 24
 write
continue 




-enjoy
