### ISSUE TITLE
Reading inputs from unity

### ISSUE THREAD

**Issue by glupeksha** [ashtuchkin/vive-diy-position-sensor#59]
Hi, This is not actually a issue, but I saw that you were hoping to publish a tutorial on connecting to unity. If you have done so, can you please provide me the link, else is it possible for you to explain how it could be done? 

I already tried to read through Serial Port, but It won't open the port. I think the issue is that the port is used to write the output to terminal.(Just guessed) Is there is a way to do it?

**Comment by ashtuchkin** [comment]
Yeah I think I used serial port in Unity, but I don't remember how exactly.
