### ISSUE TITLE
confused about normal verctor described by 'Position calculation in detail'

### ISSUE THREAD

**Issue by poaongithub** [ashtuchkin/vive-diy-position-sensor#60]
Hi,
refer to left-hand coordinate and the illustration, the normal vector of the YZ plane is (0, cos(angle_hor), -sin(angle_hor)), rather than (0, cos(angle_hor), sin(angle_hor)),  Z axis value always negative, right? I don't know whether it's correct or not, thanks.

**Comment by ashtuchkin** [comment]
that depends on the direction of rotation, the drawing is representing it backwards. In the code I use (0, cos(angle_hor), sin(angle_hor)).
