### ISSUE TITLE
tyc monitor only giving 000000 as values not giving coordinates

### ISSUE THREAD

**Issue by rajattyagi134** [ashtuchkin/vive-diy-position-sensor#62]
Or do you have a different output when you press enter?
btw this is an example configuration i used. Thought you should use your own Rotationmatrixes [(This might help you if you don't know how)](https://github.com/ashtuchkin/vive-diy-position-sensor-geometry-getter)

reset  
sensor0 pin 12 positive  
base0 origin -1.099456 2.181808 1.686393 matrix 0.775341 0.268522 -0.571613 -0.006164 0.908281 0.418314 0.631512 -0.320813 0.705883  
base1 origin 1.467740 2.275151 -1.877902 matrix -0.730416 -0.392384 0.559041 -0.009979 0.824549 0.565703 -0.682930 0.407620 -0.606179  
object0 sensor0  
stream0 position object0 > usb_serial  
stream1 angles > usb_serial  
serial1 57600  
stream2 mavlink object0 ned 110 > serial1  
write  
continue  
o  

ps: the 'o' param will throw you into the debug mode, but after configuration everything, you can get some outputs from there (check the command list you linked)

_Originally posted by @koen1993 in https://github.com/ashtuchkin/vive-diy-position-sensor/issues/53#issuecomment-400212234_

**Comment by ashtuchkin** [comment]
not sure what's the issue here
