### ISSUE TITLE
hello,thanks for the sharing.  And if i want to use this 3d position data(Mavlink ATT_POS_MOCAP via serial), how to config parameters of PX4?

### ISSUE THREAD

**Issue by ajiangdaye** [ashtuchkin/vive-diy-position-sensor#63]

**Comment by r1b4z01d** [comment]
Were you able to connect your sensor to PX4?

**Comment by ajiangdaye** [comment]
> Were you able to connect your sensor to PX4?

yes. it worked.

**Comment by brandohando** [comment]
How did you connect it to the pixhawk @ajiangdaye ? Did you connect from the teensy to which port on the pixhawk? UART?

**Comment by ajiangdaye** [comment]
> How did you connect it to the pixhawk @ajiangdaye ? Did you connect from the teensy to which port on the pixhawk? UART?

yes.

**Comment by brandohando** [comment]
@ajiangdaye thanks! Was this from the micro usb on the teensy straight to the UART?
