### ISSUE TITLE
how to embedded imu with this project? any small suggestion will be helpful

### ISSUE THREAD

**Issue by jayaramanrp** [ashtuchkin/vive-diy-position-sensor#64]

**Comment by ashtuchkin** [comment]
This would require significant changes to the codebase, but you can probably start with adjusting the pipeline (https://github.com/ashtuchkin/vive-diy-position-sensor/blob/master/src/vive_sensors_pipeline.cpp) to add IMU-related nodes there. You'll probably have to implement something like Kalman filter to fuse the data from IMU and this position sensor.

Sorry I'm pretty busy at the moment and can't assist you deeper.
