### ISSUE TITLE
Questions: Trying to reproduce the setup

### ISSUE THREAD

**Issue by imuguruza** [ashtuchkin/vive-diy-position-sensor#7]
Hey there,

I'm trying to reproduce your results. Firstly I'm checking that the hardware I have mounted is OK. I have reproduced you schematics in a board that looks like this:

![img_20161215_170423](https://cloud.githubusercontent.com/assets/7628788/21231505/c62bc62c-c2e8-11e6-9f7e-8ed7ef1f100d.jpg)

I have placed 2 photodiodes, turned ~180º a positioned one of each lighthouses in fron of each photodiode. Once turned on, I'm seeing the next signal at the output of the 2nd OpAmp:

![scope_4](https://cloud.githubusercontent.com/assets/7628788/21232042/9c578aaa-c2ea-11e6-8b8d-3d1e2b5071df.png)

Classifying the signals:
![lighthouse_compl](https://cloud.githubusercontent.com/assets/7628788/21232761/157f7242-c2ed-11e6-9b99-0e0fa58cb5c3.png)

(I have seen that there are 4 different group of pulses and starts over again)

I have noted down sync pulses and hits. As can be observed, in the 3rd & 4th, there are two hits. I'm not sure why this happens.

This are my doubts:

- The 2 sync pulses are not separated in 400us, I'm seeing ~2.4ms:
- In 3rd and 4th group of pulse, I'm seeing 4 pulses( 2x sync + 2x hits), does this means I'm seeing a kind of reflection or that in that period I'm reading in both photodiodes the ray which has been sent by one of the lightshouse? Are you also reading something like this?

As far as I understand, the pulses generated using 2 lighthouses are:

- 1x sync (lighthouse A) + 1x sync (lighthouse B) + 1x Horizontal lighthouse A
- 1x sync (lighthouse A) + 1x sync (lighthouse B) + 1x Vertical lighthouse A
- 1x sync (lighthouse A) + 1x sync (lighthouse B) + 1x Horizontal lighthouse B
- 1x sync (lighthouse A) + 1x sync (lighthouse B) + 1x Vertical lighthouse B

Calculation wise, I do not have clear if knowing the source of each pulse if its crutial or not. Meaning if it is important to know if the ray has been generated by lighthouse A or B and if we need to know if it's a vertical or horizontal. Is there any way of knowing this? Is it crutial?

Great job btw

**Comment by ashtuchkin** [comment]
Hey, great job, it's almost working! From the pictures you posted, it looks like the stations are not in sync - the distance between pulses should be ~400us, I've never seen it different. Is the current setup working with the Vive? Do both stations have green LEDs? Do you have one of them set to "B" and the other to "C"?

> In 3rd and 4th group of pulse, I'm seeing 4 pulses( 2x sync + 2x hits), does this means I'm seeing a kind of reflection or that in that period I'm reading in both photodiodes the ray which has been sent by one of the lightshouse? Are you also reading something like this?

Probably reflection or sync problems. When it's the same sweep, the difference between pulses is on the order of 10us.

> As far as I understand, the pulses generated using 2 lighthouses are: ...

Yes, that's right.

> Calculation wise, I do not have clear if knowing the source of each pulse if its crutial or not. Meaning if it is important to know if the ray has been generated by lighthouse A or B and if we need to know if it's a vertical or horizontal. Is there any way of knowing this? Is it crutial?

Well, it's crucial to map it to geometry to get the actual position. It's easy to determine which sync pulse is coming from which station by analyzing their width, see table on [this page](https://github.com/nairol/LighthouseRedox/blob/master/docs/Light%20Emissions.md). skip is station, rotor is horizontal/vertical. data can be ignored.

**Comment by imuguruza** [comment]
>From the pictures you posted, it looks like the stations are not in sync - the distance between pulses should be ~400us, I've never seen it different. Is the current setup working with the Vive? Do both stations have green LEDs? Do you have one of them set to "B" and the other to "C"?

You're right, I had the stations ins "A" and "B". I have switched to "B" abd "C" and now I'm seeing the pulses right. The sync pulses with a delay of 400us and a sinlge hit per sweep

**Comment by imuguruza** [comment]
>Well, it's crucial to map it to geometry to get the actual position. It's easy to determine which sync pulse is coming from which station by analyzing their width, see table on this page. skip is station, rotor is horizontal/vertical. data can be ignored.

So if I get it, it means that:

- j0 & j1 -> Active lighthouse & Vertical sweep.
- k0 & k1 -> Active lighthouse & Horizontal sweep.
- j2 & j3 -> Inactive lighthouse & Vertical sweep.
- k2 & k3 -> Inactive lighthouse & Horizontal sweep.

So I should never see, in the same sweep, two sync pulses that belongs to j0/1 or k0/k1.
I have observed that "inactive" sync width signals happens for both sync signals and that photosensors also reads ray. Should we ignore this event??

**Comment by ashtuchkin** [comment]
It should be
'''
"active" sync station B -> "inactive" sync station C -> horizontal sweep
pulse station B
.. same .. vertical pulse
"Inactive" sync station B -> "active" sync station C -> horizontal sweep
pulse station C
.. same.. vertical
'''

Also keep in mind that pulse lengths in that table are not absolute -
because of the filters and non-ideal opamps it can differ, but all in the
same amount. I have some code to adjust it in the repo.

**Comment by imuguruza** [comment]
Yeah, now I'm able to see pulses correctly. They follow the pattern you mentioned, so it's time to see if I can calculate the position
Thanks for you help!
