### ISSUE TITLE
output data

### ISSUE THREAD

**Issue by amralabsi** [ashtuchkin/vive-diy-position-sensor#71]
I was wonder if there is a way to print out the x, y, z coordinates only without anything else on the tycmd monitor?

**Comment by ashtuchkin** [comment]
Sure just change the code.

**Comment by amralabsi** [comment]
I am not sure what can I change in the code to get it to print that way i read almost every file in it but i am still not sure can you point me to the folder name or file name please? I want the output to be just the x y z because I am sending it to my phone over hm10.

**Comment by ashtuchkin** [comment]
This is where the position is printed:
https://github.com/ashtuchkin/vive-diy-position-sensor/blob/master/src/formatters.cpp#L56

--
Alexander Shtuchkin
