### ISSUE TITLE
Question about OpenVR

### ISSUE THREAD

**Issue by emo10001** [ashtuchkin/vive-diy-position-sensor#72]
Hey @ashtuchkin 

You'll have to excuse my ignorance on this, but would this be tracked with OpenVR/SteamVR like a Vive tracker?  I'm interested in making something that would work with this software from Brekel:

https://brekel.com/openvr-recorder/

Is it as simple as assembling the parts and embedding the software or would there be other steps needed for it to be found by this software and/or the Vive software?

Awesome stuff.  Thanks so much!

Eric

**Comment by ashtuchkin** [comment]
This project is much more low-level. It does give you current 3d coordinates with some precision, but it's nowhere near the stability of the original Vive trackers. You'll also need to get these coordinates to your computer somehow (currently the coordinates are calculated on the device itself).
