### ISSUE TITLE
Increase precision

### ISSUE THREAD

**Issue by toncho11** [ashtuchkin/vive-diy-position-sensor#74]
Hi,

How can the precision be increased? It seems like 1 cm which is not enough for us.

**Comment by ashtuchkin** [comment]
It can't be increased, you'll have to use a different solution.

**Comment by toncho11** [comment]
But you say:

"3d position accuracy: currently ~10mm; less than 2mm possible with additional work."

What is this additional work?

**Comment by LeeCookGHA** [comment]
Increase the number of photo detectors, some additional sensors and then use
https://github.com/cntools/libsurvive for pose estimation.

**Comment by ashtuchkin** [comment]
Yep you'll need multiple sensors, certainly not DIY (TS3633-CM1
<https://www.triadsemi.com/product/ts3633-cm1/> work much better), and then
you'll need to do additional research on how to fuse their data.

**Comment by luoxz-ai** [comment]
Can't buy TS3633-CM1 devices anymore
