### ISSUE TITLE
Compatability with other microprocessors?

### ISSUE THREAD

**Issue by LittleNyanCat** [ashtuchkin/vive-diy-position-sensor#77]
The teensy 3.2 can be quite expensive, especially for us overseas folks, is there something preventing the code from being ported to another microcontroller such as the ESP32? 
It seems to have specs about on par if not better, and it's wireless capabilities are very enticing for potential VR projects of mine (and quite a few others)

**Comment by ashtuchkin** [comment]
I'm not familiar with ESP32, so can't tell for sure, but it seems doable.
Make sure the chip has good hardware timers with at at least .5-1 ns
precision.
