### ISSUE TITLE
Time offset doubt

### ISSUE THREAD

**Issue by imuguruza** [ashtuchkin/vive-diy-position-sensor#8]
Hey there,
I continue understanding how the calculations works.
Just a detail that I'm not sure:
Following the [calculation page](https://github.com/ashtuchkin/vive-diy-position-sensor/wiki/Position-calculation-in-detail), I have a doubt about the timing called `< time offset in us>`.

Is supposed the timing since the sync pulse is generated, or is ended?
I think graphically explained is more clear, this value is `x`, `y`or `z` delay (in us)?

![img_20161220_172056](https://cloud.githubusercontent.com/assets/7628788/21358405/e3000c2e-c6d8-11e6-868a-d311aacc1c06.jpg)

I don't see it in the sourcecode...

Thanks!

**Comment by ashtuchkin** [comment]
Great question! It's Z. We start the "cycle" when the first sync pulse
starts.

Note, that this is independent on which station is currently
laser-sweeping, the timing is always counted from the first sync pulse,
which can be produced by a different station.

--
Alexander Shtuchkin

**Comment by imuguruza** [comment]
OK, thanks for the info
